require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CostCentresController do

  # This should return the minimal set of attributes required to create a valid
  # CostCentre. As you add validations to CostCentre, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all cost_centres as @cost_centres" do
      cost_centre = CostCentre.create! valid_attributes
      get :index
      assigns(:cost_centres).should eq([cost_centre])
    end
  end

  describe "GET show" do
    it "assigns the requested cost_centre as @cost_centre" do
      cost_centre = CostCentre.create! valid_attributes
      get :show, :id => cost_centre.id.to_s
      assigns(:cost_centre).should eq(cost_centre)
    end
  end

  describe "GET new" do
    it "assigns a new cost_centre as @cost_centre" do
      get :new
      assigns(:cost_centre).should be_a_new(CostCentre)
    end
  end

  describe "GET edit" do
    it "assigns the requested cost_centre as @cost_centre" do
      cost_centre = CostCentre.create! valid_attributes
      get :edit, :id => cost_centre.id.to_s
      assigns(:cost_centre).should eq(cost_centre)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CostCentre" do
        expect {
          post :create, :cost_centre => valid_attributes
        }.to change(CostCentre, :count).by(1)
      end

      it "assigns a newly created cost_centre as @cost_centre" do
        post :create, :cost_centre => valid_attributes
        assigns(:cost_centre).should be_a(CostCentre)
        assigns(:cost_centre).should be_persisted
      end

      it "redirects to the created cost_centre" do
        post :create, :cost_centre => valid_attributes
        response.should redirect_to(CostCentre.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cost_centre as @cost_centre" do
        # Trigger the behavior that occurs when invalid params are submitted
        CostCentre.any_instance.stub(:save).and_return(false)
        post :create, :cost_centre => {}
        assigns(:cost_centre).should be_a_new(CostCentre)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CostCentre.any_instance.stub(:save).and_return(false)
        post :create, :cost_centre => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cost_centre" do
        cost_centre = CostCentre.create! valid_attributes
        # Assuming there are no other cost_centres in the database, this
        # specifies that the CostCentre created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CostCentre.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => cost_centre.id, :cost_centre => {'these' => 'params'}
      end

      it "assigns the requested cost_centre as @cost_centre" do
        cost_centre = CostCentre.create! valid_attributes
        put :update, :id => cost_centre.id, :cost_centre => valid_attributes
        assigns(:cost_centre).should eq(cost_centre)
      end

      it "redirects to the cost_centre" do
        cost_centre = CostCentre.create! valid_attributes
        put :update, :id => cost_centre.id, :cost_centre => valid_attributes
        response.should redirect_to(cost_centre)
      end
    end

    describe "with invalid params" do
      it "assigns the cost_centre as @cost_centre" do
        cost_centre = CostCentre.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CostCentre.any_instance.stub(:save).and_return(false)
        put :update, :id => cost_centre.id.to_s, :cost_centre => {}
        assigns(:cost_centre).should eq(cost_centre)
      end

      it "re-renders the 'edit' template" do
        cost_centre = CostCentre.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CostCentre.any_instance.stub(:save).and_return(false)
        put :update, :id => cost_centre.id.to_s, :cost_centre => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cost_centre" do
      cost_centre = CostCentre.create! valid_attributes
      expect {
        delete :destroy, :id => cost_centre.id.to_s
      }.to change(CostCentre, :count).by(-1)
    end

    it "redirects to the cost_centres list" do
      cost_centre = CostCentre.create! valid_attributes
      delete :destroy, :id => cost_centre.id.to_s
      response.should redirect_to(cost_centres_url)
    end
  end

end
